-- For Everest meta in bin system

local defaultMetadata = {}

defaultMetadata.meta = {
    --"Name" = "", -- Better to let Everest decide
    --"SID" = "", -- Better to let Everest decide
    Icon = "",

    Interlude = false,
    --"CompleteScreenName" = "", -- Better to let Everest decide

    --"CassetteCheckpointIndex" = 0, -- Better to let Everest decide

    TitleBaseColor = "6c7c81",
    TitleAccentColor = "2f344b",
    TitleTextColor = "ffffff",

    IntroType = "WakeUp",

    Dreaming = false,

    ColorGrade = "",

    Wipe = "",

    DarknessAlpha = 0.05,
    BloomBase = 0.0,
    BloomStrength = 1.0,

    --"Jumpthru" = "", -- Done on a per entity basis in editor, not useful for us

    CoreMode = "",

    --"CassetteNoteColor" = "",
    CassetteSong = "",

    ForegroundTiles = "",
    BackgroundTiles = "",
    AnimatedTiles = "",
    Portraits = "",
    Sprites = "",

    OverrideASideMeta = false,

    PostcardSoundID = ""
}

defaultMetadata.mode = {
    IgnoreLevelAudioLayerData = false,
    Inventory = "Default",
    --"Path" = "", -- We have allready loaded the file, this can always be null
    --"PoemID" = "", -- Autogenerated by Everest

    StartLevel = "",
    HeartIsEnd = false,

    SeekerSlowdown = true,
    TheoInBubble = false
}

defaultMetadata.audioState = {
    Ambience = "event:/env/amb/01_main",
    Music = "event:/music/lvl1/main"
}

return defaultMetadata