return {
    env_amb_00_main = "event:/env/amb/00_prologue",
    env_amb_01_main = "event:/env/amb/01_main",
    env_amb_02_awake = "event:/env/amb/02_awake",
    env_amb_02_dream = "event:/env/amb/02_dream",
    env_amb_03_exterior = "event:/env/amb/03_exterior",
    env_amb_03_interior = "event:/env/amb/03_interior",
    env_amb_03_pico8_closeup = "event:/env/amb/03_pico8_closeup",
    env_amb_04_main = "event:/env/amb/04_main",
    env_amb_05_interior_dark = "event:/env/amb/05_interior_dark",
    env_amb_05_interior_main = "event:/env/amb/05_interior_main",
    env_amb_05_mirror_sequence = "event:/env/amb/05_mirror_sequence",
    env_amb_06_lake = "event:/env/amb/06_lake",
    env_amb_06_main = "event:/env/amb/06_main",
    env_amb_06_prehug = "event:/env/amb/06_prehug",
    env_amb_09_main = "event:/env/amb/09_main",
    env_amb_worldmap = "event:/env/amb/worldmap",
    env_amb_10_rain = "event:/new_content/env/10_rain",
    env_amb_10_electricity = "event:/new_content/env/10_electricity",
    env_amb_10_endscene = "event:/new_content/env/10_endscene",
    env_amb_10_rushingvoid = "event:/new_content/env/10_rushingvoid",
    env_amb_10_space_underwater = "event:/new_content/env/10_space_underwater",
    env_amb_10_voidspiral = "event:/new_content/env/10_voidspiral",
    env_amb_10_grannyclouds = "event:/new_content/env/10_grannyclouds",
}