return {
    env_loc_02_lamp = "event:/env/local/02_old_site/phone_lamp",
    env_loc_03_brokenwindow_large_loop = "event:/env/local/03_resort/broken_window_large",
    env_loc_03_brokenwindow_small_loop = "event:/env/local/03_resort/broken_window_small",
    env_loc_03_pico8machine_loop = "event:/env/local/03_resort/pico8_machine",
    env_loc_07_flag_flap = "event:/env/local/07_summit/flag_flap",
    env_loc_09_conveyer_idle = "event:/env/local/09_core/conveyor_idle",
    env_loc_09_fireball_idle = "event:/env/local/09_core/fireballs_idle",
    env_loc_09_lavagate_idle = "event:/env/local/09_core/lavagate_idle",
    env_loc_campfire_loop = "event:/env/local/campfire_loop",
    env_loc_campfire_start = "event:/env/local/campfire_start",
    env_loc_waterfall_big_in = "event:/env/local/waterfall_big_in",
    env_loc_waterfall_big_main = "event:/env/local/waterfall_big_main",
    env_loc_waterfall_small_in_deep = "event:/env/local/waterfall_small_in_deep",
    env_loc_waterfall_small_in_shallow = "event:/env/local/waterfall_small_in_shallow",
    env_loc_waterfall_small_main = "event:/env/local/waterfall_small_main",
    env_loc_10_cafe_computer = "event:/new_content/env/local/cafe_computer",
    env_loc_10_cafe_sign = "event:/new_content/env/local/cafe_sign",
    env_loc_10_tutorial_static_left = "event:/new_content/env/local/tutorial_static_left",
    env_loc_10_tutorial_static_right = "event:/new_content/env/local/tutorial_static_right",
    env_loc_10_kevinpc = "event:/new_content/env/local/kevinpc",
}